import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('src/index.html','utf8');
const js=fs.readFileSync('src/app.js','utf8');
assert.match(html,/accept="image\/\*"/);
assert.match(html,/capture="environment"/);
assert.match(html,/UNKNOWN/);
assert.match(html,/id="whole"/);assert.match(html,/id="flower"/);assert.match(html,/id="leaf"/);assert.match(html,/id="detail"/);
assert.match(js,/Motore botanico validato non installato/);
assert.match(js,/localStorage\.setItem\(STORAGE_KEY/);
assert.match(js,/status: 'UNKNOWN'/);
assert.match(js,/speciesCount\.textContent = '0'/);
assert.match(js,/readAsDataURL\(file\)/);
assert.match(js,/MAX_IMAGE_EDGE = 1600/);
assert.match(js,/JPEG_QUALITY = 0\.78/);
assert.match(js,/canvas\.toDataURL\('image\/jpeg', JPEG_QUALITY\)/);
assert.match(js,/Math\.min\(1, MAX_IMAGE_EDGE/);
assert.match(js,/QuotaExceededError/);
assert.match(js,/evidence,/);
assert.match(js,/image: canvas\.toDataURL/);
assert.match(js,/salvate solo su questo dispositivo/);
assert.doesNotMatch(html,/\b\d{1,3}%\b/);
assert.doesNotMatch(js,/status:\s*['"]VERIFIED['"]/);
console.log('HERBARIUM smoke PASS');
