import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('src/index.html','utf8');
const js=fs.readFileSync('src/app.js','utf8');
assert.match(html,/accept="image\/\*"/);
assert.match(html,/capture="environment"/);
assert.match(html,/UNKNOWN/);
assert.match(html,/id="whole"/);assert.match(html,/id="flower"/);assert.match(html,/id="leaf"/);assert.match(html,/id="detail"/);
assert.match(js,/Motore botanico validato non installato/);
assert.match(js,/indexedDB\.open\(DB_NAME, 1\)/);
assert.match(js,/createObjectStore\(STORE_NAME, \{ keyPath: 'id' \}\)/);
assert.match(js,/objectStore\(STORE_NAME\)\.add\(observation\)/);
assert.match(js,/objectStore\(STORE_NAME\)\.getAll\(\)/);
assert.match(js,/status: 'UNKNOWN'/);
assert.match(js,/speciesCount\.textContent = '0'/);
assert.match(js,/readAsDataURL\(file\)/);
assert.match(js,/file\.type && !file\.type\.startsWith\('image\/'\)/);
assert.match(js,/MAX_INPUT_BYTES = 12 \* 1024 \* 1024/);
assert.match(js,/file\.size && file\.size > MAX_INPUT_BYTES/);
assert.match(js,/MAX_IMAGE_EDGE = 1600/);
assert.match(js,/JPEG_QUALITY = 0\.78/);
assert.match(js,/canvas\.toBlob/);
assert.match(js,/Math\.min\(1, MAX_IMAGE_EDGE/);
assert.match(js,/blob: await canvasToBlob\(canvas\)/);
assert.match(js,/database locale del dispositivo/);
assert.match(js,/offline · dati locali/);
assert.match(js,/online · dati locali/);
assert.match(js,/Nessun dato è stato salvato/);
assert.match(js,/Nessuna osservazione incompleta è stata registrata/);
assert.match(js,/Controlla lo spazio disponibile e riprova/);
assert.doesNotMatch(js,/localStorage\.setItem/);
assert.doesNotMatch(html,/\b\d{1,3}%\b/);
assert.doesNotMatch(js,/status:\s*['"]VERIFIED['"]/);
console.log('HERBARIUM smoke PASS');
