import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('src/index.html','utf8');
const js=fs.readFileSync('src/app.js','utf8');
assert.match(html,/accept="image\/\*"/);assert.match(html,/capture="environment"/);assert.match(html,/UNKNOWN/);
assert.match(html,/id="whole"/);assert.match(html,/id="flower"/);assert.match(html,/id="leaf"/);assert.match(html,/id="detail"/);
assert.match(html,/id="collection"/);assert.match(html,/id="collectionList"/);assert.match(html,/Solo dati locali/);assert.match(html,/Nessun dato fittizio/);
assert.match(html,/id="book"/);assert.match(html,/id="pendingList"/);assert.match(html,/Solo dati reali/);assert.match(html,/Nessuna certezza inventata/);
assert.match(html,/id="atlas"/);assert.match(html,/id="atlasRegions"/);assert.match(html,/Nessun cloud/);assert.match(html,/Privacy geografica/);
assert.match(js,/Motore botanico validato non installato/);assert.match(js,/indexedDB\.open\(DB_NAME,1\)/);assert.match(js,/objectStore\(STORE_NAME\)\.add\(observation\)/);assert.match(js,/objectStore\(STORE_NAME\)\.getAll\(\)/);
assert.match(js,/status:'UNKNOWN'/);assert.match(js,/speciesCount\.textContent='0'/);assert.match(js,/item=>item&&item\.status==='UNKNOWN'/);assert.match(js,/renderCollection/);assert.match(js,/collectionCount/);assert.match(js,/collectionVerifiedCount/);assert.match(js,/Nessuna osservazione reale salvata/);assert.match(js,/Impossibile leggere la raccolta locale/);assert.match(js,/renderBook/);assert.match(js,/renderAtlas/);
assert.match(js,/await renderCollection\(\)/);assert.match(js,/button\.dataset\.view==='collection'/);assert.match(js,/renderStats\(\);renderCollection\(\);renderBook\(\);renderAtlas\(\)/);
assert.match(js,/readAsDataURL\(file\)/);assert.match(js,/file\.type&&!file\.type\.startsWith\('image\/'\)/);assert.match(js,/MAX_INPUT_BYTES=12\*1024\*1024/);assert.match(js,/MAX_IMAGE_EDGE=1600/);assert.match(js,/JPEG_QUALITY=0\.78/);assert.match(js,/canvas\.toBlob/);
assert.match(js,/database locale del dispositivo/);assert.match(js,/offline · dati locali/);assert.match(js,/online · dati locali/);assert.match(js,/Nessun dato è stato salvato/);assert.match(js,/Nessuna osservazione incompleta è stata registrata/);
assert.doesNotMatch(js,/localStorage\.setItem/);assert.doesNotMatch(html,/\b\d{1,3}%\b/);assert.doesNotMatch(js,/status:\s*['"]VERIFIED['"]/);assert.doesNotMatch(js,/fake|mockSpecies|starterPlants/i);assert.doesNotMatch(js,/fetch\(|XMLHttpRequest|navigator\.geolocation/);
console.log('HERBARIUM smoke PASS');
